name: Shellcheck

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master

